### ISSUE TITLE
Instructions are unclear

### ISSUE THREAD

**Issue by anttikantee** [deferpanic/gorump#2]
The relationship between "Getting started" and the README in examples is not clear (or at least I would assume it to not be clear for the casual reader).

Probably should provide ~copypasteable step-by-step instructions in one place.

**Comment by oren** [comment]
I tried following the readme and everything went smooth. i just don't know what to do next (:

I have 2 folders:
one with main.go

```
package main

import (
        "io"
        "net/http"
)

func handler(w http.ResponseWriter, r *http.Request) {
        io.WriteString(w, "hello, world!\n")
}

func main() {
        http.HandleFunc("/", handler)
        http.ListenAndServe(":3000", nil)
}
```

in this folder i ran `CC=x86_64-rumprun-netbsd-gcc CGO_ENABLED=1 GOOS=netbsd /usr/local/go/bin/go build -buildmode=c-archive -v`

the other folder is rumprun and the last output is: `./build-rr.sh ran successfully`.

what's my next step?

**Comment by oren** [comment]
also, it would be nice to add some links that explain about unikernels and rumprun.

**Comment by anttikantee** [comment]
How I did it is the "download rumprun" part from the front page, then follow the instructions under `examples`.

Yea links sound like a good idea.

**Comment by eyberg** [comment]
hi @oren - I just updated the instructions to be more clear/explicit

can you try them out https://github.com/deferpanic/gorump and lmk how it goes?

essentially, if you have built rumprun and baked the binary then you just need to add networking && launch it via qemu or kvm.

**Comment by oren** [comment]
a few questions/issues:
1. `tar xzf go1.5*` outputs a folder called go, not  go1.5
2.  `GOROOT_BOOTSTRAP=/usr/local/go GOOS=netbsd GOARCH=amd64 ./make.bash` - i assume i need to clone this repo and cd into the go/src folder. is that accurate?
3. is this going to replace my go installation or can i have 2 version of go at the same time

I apologize if those are basic questions. I am new to go and to unikernels.

**Comment by eyberg** [comment]
1) thanks - updated the readme
2) yep - updated the readme for that
3) I would not replace your existing go installation with this no as it's very early stage and we know we've broke quite a bit of stuff, having said that, I personally keep multiple copies of go laying around and just update the symlink as needed - if you are new to go this has might have a good chance of causing you frustration though

**Comment by oren** [comment]
works now. thanks a lot! I don't understand what all those header and c files do but that's probably outside of the scope of this repo.

one last thing you can add to the readme - just mention that 'Install the Modified Go'  section should be performed inside the root of the current repo.
