### ISSUE TITLE
go example fails to run under xen

### ISSUE THREAD

**Issue by dstrbad** [deferpanic/gorump#22]
Hi,

in Makefile I've changed `rumprun-bake hw_virtio` to `rumprun-bake xen_pv`. I've built the app and tried to start app with `rumprun xen -i hello.bin` but it throws following:

```
start_info: 0x62d000(VA)
    nr_pages: 0x4000
  shared_inf: 0x47729000(MA)
     pt_base: 0x630000(VA)
nr_pt_frames: 0x7
    mfn_list: 0x60d000(VA)
   mod_start: 0x0(VA)
     mod_len: 0
       flags: 0x0
    cmd_line:
  stack:      0x577940-0x5f7940
MM: Init
      _text: 0x0(VA)
     _etext: 0x2673ba(VA)
   _erodata: 0x3d5000(VA)
     _edata: 0x3e0618(VA)
stack start: 0x577940(VA)
       _end: 0x607da8(VA)
  start_pfn: 63a
    max_pfn: 4000
Mapping memory range 0x63a000 - 0x4000000
setting 0x0-0x3d5000 readonly
skipped 0x1000
MM: Initialise page allocator for 656000(656000)-4000000(4000000)
MM: done
Demand map pfns at 4001000-2004001000.
Initialising timer interface
Initialising console ... done.
gnttab_table mapped at 0x4001000.
xenbus initialised on irq 1 mfn 0x51e51
Failed to read device/pci/0/backend-id.
no backend
Copyright (c) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
    2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015
    The NetBSD Foundation, Inc.  All rights reserved.
Copyright (c) 1982, 1986, 1989, 1991, 1993
    The Regents of the University of California.  All rights reserved.

NetBSD 7.99.21 (RUMP-ROAST)
total memory = 29460 KB
timecounter: Timecounters tick every 10.000 msec
timecounter: Timecounter "clockinterrupt" frequency 100 Hz quality 0
cpu0 at thinair0: rump virtual cpu
root file system type: rumpfs
kern.module.path=/stand/amd64/7.99.21/modules
mainbus0 (root)
timecounter: Timecounter "bmktc" frequency 1000000000 Hz quality 100
mounted tmpfs on /tmp
Page fault at linear address 0x33330003, rip 0x547bd, regs 0xdc0de8, sp 0xdc0e90, our_sp 0xdc0dd0, code 0
Thread: lwp
RIP: e030:[<00000000000547bd>]
RSP: e02b:0000000000dc0e90  EFLAGS: 00010293
RAX: 0000000000000000 RBX: 0000000033330003 RCX: 0000000033330003
RDX: 000000000102c010 RSI: 0000000000000010 RDI: 0000000000000001
RBP: 0000000000000000 R08: 00000000000a57ff R09: 0000000000000001
R10: 000000000027a5c0 R11: 0000000000000000 R12: 0000000000000010
R13: 00000000002ed7a4 R14: 0000000000000000 R15: 0000000000000008
base is 0 Page fault in pagetable walk (access to invalid memory?).
```

I'm new to all of this so any advice is welcome. How to approach debugging of this?

Thanks

**Comment by anttikantee** [comment]
First, you might want to ask this question on the rumpkernel-users mailing list. Someone was just yesterday working on gorump on EC2 (Xen), and got it working.  Maybe they ran into the same problem before they got it working.

The way I usually start debugging is by loading the binary in gdb, and typing `l *0x%rip`, which in this case would be `l *0x547bd`. The faulting address (`0x33330003`) looks a bit weird, not sure what to make of it.  But what is going on will be clarified when you learn what code line the program was executing.

If that doesn't help, you can use `rumprun xen -D 1234 [....]` to start a gdb server (requires that you have `gdbsx` installed) and then you can attach gdb at runtime and with any luck will be able to get a stacktrace.  That said, the Xen gdbsx debugging facility has not always worked very well for me, YMMV.

**Comment by dstrbad** [comment]
I've got all examples running by increasing `kludge_argc` value in respective `*.c` files. After that change all of the examples are working both on XEN and KVM for me.

Prior to that change, code execution was failing at address `*0x547bd` which is `findnull(s *byte) int`  function (_line 16_, for loop). I've found that function in `/usr/local/go/src/runtime/string1.go` and it looks as following:

``` go
//go:nosplit
func findnull(s *byte) int {
        if s == nil {
                return 0
        }
        p := (*[_MaxMem/2 - 1]byte)(unsafe.Pointer(s))
        l := 0
        for p[l] != 0 {
                l++
        }
        return l
}
```

I'd like to push changes that I've made (increased `kludge_argc`, `Makefile` and updated `README`) but before that I would like to understand fully what exactly was happening, at the moment I'm just guessing, findnull <-> kludge_argc relation is not clear to me ;) 
Also, I see there's issue #15 so I'd be interested in that one, can someone just point me in right direction?

Thanks

**Comment by eyberg** [comment]
@dstrbad right now argc/argv is stubbed - so if they were in use at all that can cause undefined behavior - really curious how you found that

in regular amd64 go wants them during its runtime initiliazation =>

https://github.com/deferpanic/gorump/blob/8e90fa3853bca8bc5d64820b4ac308b815cb4727/go/src/runtime/rt0_linux_amd64.s#L51-L56

whereas we just stubbed them from the client side and read them in here

https://github.com/deferpanic/gorump/blob/e9928d36d34960822ecb826483c95e454f687a68/go/src/runtime/rt0_rumprun_amd64.s#L27-L34

the stack is setup as argc, list of argv, then null, then envv, etc..

def. need a better way of handling this

**Comment by marinbek** [comment]
I pinned down the issue to the argv indexing logic [here](https://github.com/deferpanic/gorump/blob/master/go/src/runtime/runtime1.go#L45):

``` go
func argv_index(argv **byte, i int32) *byte {
    return *(**byte)(add(unsafe.Pointer(argv), uintptr(i)*ptrSize))
}
```

which is used by runtime function `goenvs_unix` [which is here](https://github.com/deferpanic/gorump/blob/master/go/src/runtime/runtime1.go#L72-L85), namely, this part here dies:

``` go
        envs[i] = gostring(argv_index(argv, argc+1+i))
```

And it dies because it expect to get env there so it tries to get a string on address `0x33330003`, which is inaccessible ~~(because it is not really env)~~.

I went instruction-by-instruction of `argv_index` logic to see what I am missing:

```
=> 0x000000000004ad17 <+167>:   mov    0x5bd0bf(%rip),%edx        # 0x607ddc <runtime.argc>
   0x000000000004ad1d <+173>:   inc    %edx
   0x000000000004ad1f <+175>:   mov    %eax,0x34(%rsp)
   0x000000000004ad23 <+179>:   mov    0x428636(%rip),%rbx        # 0x473360 <runtime.argv>
                                                  // RBX is 0x3d5250, which points to 0x26d500 (first argv)
   0x000000000004ad2a <+186>:   add    %eax,%edx  //  argc+1+i ends here, result is EDX=2
   0x000000000004ad2c <+188>:   movslq %edx,%rdx  // sign extend EDX (0x2)
   0x000000000004ad2f <+191>:   shl    $0x3,%rdx  // shift, RDX == b010000 == 16
   0x000000000004ad33 <+195>:   add    %rdx,%rbx  // add 16 to argv pointer, setting RBX to 0x3d5260
                                                  // value at 0x3d5260 is 0x33330003 - not really env
   0x000000000004ad36 <+198>:   mov    (%rbx),%rbp
   0x000000000004ad39 <+201>:   mov    %rbp,(%rsp)
```

~~My feeling is that the stack is wrongly set up [here](https://github.com/deferpanic/gorump/blob/e9928d36d34960822ecb826483c95e454f687a68/go/src/runtime/rt0_rumprun_amd64.s#L27-L34) so instead of having env after argv (argv + 16) we have this `0x33330003` stored and thing goes kaboom.~~

BTW 0x33330003 seems to be:

```
(gdb) x/a 0x3d5260
0x3d5260 <runtime_init_mu>: 0x33330003
```

~~Ideas why stack would be invalid on XEN but fine elsewhere?~~

edit: stack is actually fine, **assuming that runtime_init_mu should be where it is**

**Comment by marinbek** [comment]
Oh, and regarding the fix when argc is increased to 2... Only actual change in that case is that `goenvs_unix` skips by 24 bytes (instead of 16) in that case and ends up looking for environment on `0x0` (which also seems wrong IMHO):

```
(gdb) x/x (0x3d5250 + 24)
0x3d5268 <runtime_init_mu+8>:   0x0000000000000000
```

**Comment by marinbek** [comment]
Me again :)

I compared stack of KVM and XEN:

### KVM

```
0x4f3500 == runtime.argv == **byte

(gdb) x /w 0x004f3500
0x4f3500 <runtime.argv>:    0x004e0110

(gdb) x /15xw (0x004e0110 - 32)
0x4e00f0:                   0x00000000  0x00000000  0x00000000  0x00000000
0x4e0100 <kludge_argc>:     0x00000001  0x00000000  0x00000000  0x00000000
0x4e0110 <kludge_argv>:     0x0036cfa0  0x00000000  0x0036cfa5  0x00000000
0x4e0120 <runtime_init_mu>: 0x33330003  0x00000000  0x00000000

(gdb) x /x 0x33330003
0x33330003: 0x00000000
```

### XEN

```
 # 0x473360 <runtime.argv>

(gdb) x /x 0x473360
0x473360 <runtime.argv>:    0x003d5250

(gdb) x /50w (0x003d5250 - 32)
0x3d5230 <threadq>: 0x0067bf90  0x00000000  0x00a74a70  0x00000000
0x3d5240 <kludge_argc>: 0x00000001  0x00000000  0x00000000  0x00000000
0x3d5250 <kludge_argv>: 0x0026d500  0x00000000  0x0026d505  0x00000000
0x3d5260 <runtime_init_mu>: 0x33330003  0x00000000  0x00000000  0x00000000
0x3d5270 <runtime_init_mu+16>:  0x00000000  0x00000000  0x00000000  0x00000000
0x3d5280 <runtime_init_mu+32>:  0x00000000  0x00000000  0x00000000  0x00000000

(gdb) x /x 0x33330003
0x33330003: Cannot access memory at address 0x33330003
```

So, this should confirm stack is aligned the same way, no issue there. Only issue is that on XEN `0x33330003` is not accessible, while on KVM it is normally accessible and contains 0x0 (as there is no env).

I am at a loss now why this issue with XEN...

**Comment by anttikantee** [comment]
Well, the cheap fix is to extend kludge_argv to kludge no env.

0x33330003 is accessible on hw because, uhm, see platform/hw/arch/amd64/makepagetable.awk ;-)
(I should fix that).  On Xen, the memory mapping reflects reality and causes a trap.

**Comment by marinbek** [comment]
hm, ok.. :)

Currently as I see it it looks like:

```
0: argc
0+8: 0
0+16: argv[0]
0+24: argv[1]
0+32: runtime_init_mu
```

is what is on 0+32 really envp and runtime_init_mu is 'unfortunate' to be there or is envp actually not there? 

Also what do you mean by "extend kludge_argv to kludge no env"? just add an empty string to it or add it to `go/src/runtime/rt0_rumprun_amd64.s` ?

Sorry if I'm talking bs, slowly getting out of my league :)

**Comment by marinbek** [comment]
OK, now I get what you meant @anttikantee :) 

I just extended hello.c to be like 

``` c
int kludge_argc = 1;
char *kludge_argv[] = { "foo", "bar" };
char *envp = "";
```

so it looks like this now:

```
Disassembly of section .data:

00000000003d5240 <kludge_argc>:
  3d5240:   01 00                   add    %eax,(%rax)
    ...

00000000003d5250 <kludge_argv>:
  3d5250:   20 d5                   and    %dl,%ch
  3d5252:   26 00 00                add    %al,%es:(%rax)
  3d5255:   00 00                   add    %al,(%rax)
  3d5257:   00 25 d5 26 00 00       add    %ah,0x26d5(%rip)        # 3d7932 <rumpfs_vfsops+0x52>
  3d525d:   00 00                   add    %al,(%rax)
    ...

00000000003d5260 <envp>:
  3d5260:   2b d5                   sub    %ebp,%edx
  3d5262:   26 00 00                add    %al,%es:(%rax)
    ...

00000000003d5280 <runtime_init_mu>:
```

and finally it works on xen! wohoo :) This also fixes the issue on hw (since it was pretty much "luck" that it worked).

I'll make a separate pull-request for this...

**Comment by eyberg** [comment]
thanks!
