### ISSUE TITLE
fix time.Sleep

### ISSUE THREAD

**Issue by eyberg** [deferpanic/gorump#30]
https://github.com/deferpanic/gorump/issues/26

**Comment by ilackarms** [comment]
the problem with time.Sleep is that you are checking the return value of https://github.com/deferpanic/gorump/blob/master/go/src/runtime/os1_rumprun.go#L70 `lwp_park` but there is no way to check `errno`, so we are stuck looping forever.

see https://github.com/rumpkernel/rumprun/blob/master/lib/librumprun_base/_lwp.c#L249

**Comment by eyberg** [comment]
I saw your fix - https://github.com/emc-advanced-dev/unik/blob/ba94d0e1fced8e8c9c509912b4eb010ca3d35ba7/containers/compilers/rump/go/fixgo.sh - want to make a PR?

**Comment by ilackarms** [comment]
sure, but our solution is a hack. we should be checking `errno`, but I'm not sure how we can do that. If we had access to `cgo` stuff from `runtime`, it would be possible (see https://golang.org/cmd/cgo/:

> Any C function (even void functions) may be called in a multiple assignment context to retrieve both the return value (if any) and the C errno variable as an error (use _ to skip the result value if the function returns void).

However, `runtime` compiles before `C` and can't import from cgo, as far as I can tell.

I'll go ahead and create a pull request

**Comment by eyberg** [comment]
oh I agree - it's definitely a hack but since this is in a build specific file I don't think it's a huge problem for now, one of the longer term issues w/this project is figuring out how to make changes whilst at the same time being as close to upstream as possible

**Comment by eyberg** [comment]
https://github.com/deferpanic/gorump/pull/33

**Comment by eyberg** [comment]
closing for now
