### ISSUE TITLE
gorump on Mac OS X

### ISSUE THREAD

**Issue by christopherhesse** [deferpanic/gorump#31]
Hi!  I think I almost have gorump working on Mac OS X.  Something seems slightly off though, because I can't build the hello world example.  Building a normal rumprun C thing seems to work fine, but using gorump, I can't get it to link.

go build (seems to work fine): https://gist.github.com/christopherhesse/c5e1257284feb755db36
gcc (fails to link): https://gist.github.com/christopherhesse/10f031c614dcc7d1276e

If I use a .a file I built on a linux machine, the linking process works fine (I haven't tested actually running it).

I've attached the two archive files:

[hello-linux.a.zip](https://github.com/deferpanic/gorump/files/170675/hello-linux.a.zip)
[hello-mac.a.zip](https://github.com/deferpanic/gorump/files/170674/hello-mac.a.zip)

They seem pretty similar in size and everything, file thinks they are slightly different:
file hello-mac.a
hello-mac.a: current ar archive random library
file hello-linux.a
hello-linux.a: current ar archive

Any ideas? Am I missing some command line flag somewhere?

**Comment by eyberg** [comment]
I haven't built on osx yet - https://github.com/rumpkernel/wiki/wiki/Howto%3A-Set-up-a-Rumprun-toolchain-in-Mac-OS-X - I think someone was asking for this on the mailing list a while back but I couldn't immediately find it - https://www.freelists.org/archive/rumpkernel-users

**Comment by christopherhesse** [comment]
The rumprun toolchain seems to work fine, it looks like my copy of gorump outputs some somehow incompatible .a file.

**Comment by christopherhesse** [comment]
I think I found the problem.  gorump uses the system ar, which is not similar enough apparently to the one expected by rumprun's x86_64-rumprun-netbsd-gcc.  This command:

```
  CGO_ENABLED=1 GOOS=rumprun go build -buildmode=c-archive -v -a -x hello.go
```

Should probably be

```
 CGO_ENABLED=1 GOOS=rumprun go build -ldflags '-extar <path to netbsd ar>' -buildmode=c-archive -v -a -x hello.go
```

Except that go 1.5 doesn't support extar, so I had to just put the netbsd ar into my path instead.

**Comment by eyberg** [comment]
if that works for you - feel free to open a PR for new instructions on building
