### ISSUE TITLE
Unikernel for Singularity?

### ISSUE THREAD

**Issue by benepo** [deferpanic/gorump#47]
With Docker working to run their containers on bare metal, I was curious if gorump could be used to create a unikernel that ran Singularity (http://singularity.lbl.gov).  I know it's probably easier just to run the microservice itself as a unikernel so this is more of an academic curiosity.

**Comment by eyberg** [comment]
sorry for the late reply ben, here are my thoughts:

1) singularity is written in c and gorump is for go based unikernels so if you wanted to port/run singularity itself you'd just use rumprun base which is actually easier with c

2) I don't have a ton of exp. with singularity but a lot of the patterns/workflows I see involve shelling into the containers and running ad-hoc commands, while anything is technically possible this diminishes a lot of benefits that unikernels bring by having to hack around them

so to answer your question - yes you could do what your proposing but I think it would wind up as a completely new project/codebase, happy to chat offline further about it cause you are not the first person that has asked
